-- +goose Up
ALTER TABLE urls ADD COLUMN created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE urls ADD COLUMN updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE urls DROP COLUMN IF EXISTS created_at;
ALTER TABLE urls DROP COLUMN IF EXISTS updated_at;
