// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/surl/api.proto

package surl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRestrictedUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Alias         *string                `protobuf:"bytes,2,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRestrictedUrlRequest) Reset() {
	*x = ShortenRestrictedUrlRequest{}
	mi := &file_api_v1_surl_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRestrictedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRestrictedUrlRequest) ProtoMessage() {}

func (x *ShortenRestrictedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_surl_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRestrictedUrlRequest.ProtoReflect.Descriptor instead.
func (*ShortenRestrictedUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_surl_api_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRestrictedUrlRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ShortenRestrictedUrlRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type ShortenRetristedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRetristedUrlResponse) Reset() {
	*x = ShortenRetristedUrlResponse{}
	mi := &file_api_v1_surl_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRetristedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRetristedUrlResponse) ProtoMessage() {}

func (x *ShortenRetristedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_surl_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRetristedUrlResponse.ProtoReflect.Descriptor instead.
func (*ShortenRetristedUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_surl_api_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenRetristedUrlResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *ShortenRetristedUrlResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

var File_api_v1_surl_api_proto protoreflect.FileDescriptor

const file_api_v1_surl_api_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/surl/api.proto\x12\asurl.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\x1bShortenRestrictedUrlRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x19\n" +
	"\x05alias\x18\x02 \x01(\tH\x00R\x05alias\x88\x01\x01B\b\n" +
	"\x06_alias\"Y\n" +
	"\x1bShortenRetristedUrlResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl2\x80\x01\n" +
	"\x18RestrictedShortenService\x12d\n" +
	"\x14ShortenRestrictedUrl\x12$.surl.v1.ShortenRestrictedUrlRequest\x1a$.surl.v1.ShortenRetristedUrlResponse\"\x00B$Z\"github.com/nzwice/surl/api/v1/surlb\x06proto3"

var (
	file_api_v1_surl_api_proto_rawDescOnce sync.Once
	file_api_v1_surl_api_proto_rawDescData []byte
)

func file_api_v1_surl_api_proto_rawDescGZIP() []byte {
	file_api_v1_surl_api_proto_rawDescOnce.Do(func() {
		file_api_v1_surl_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_surl_api_proto_rawDesc), len(file_api_v1_surl_api_proto_rawDesc)))
	})
	return file_api_v1_surl_api_proto_rawDescData
}

var file_api_v1_surl_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_surl_api_proto_goTypes = []any{
	(*ShortenRestrictedUrlRequest)(nil), // 0: surl.v1.ShortenRestrictedUrlRequest
	(*ShortenRetristedUrlResponse)(nil), // 1: surl.v1.ShortenRetristedUrlResponse
}
var file_api_v1_surl_api_proto_depIdxs = []int32{
	0, // 0: surl.v1.RestrictedShortenService.ShortenRestrictedUrl:input_type -> surl.v1.ShortenRestrictedUrlRequest
	1, // 1: surl.v1.RestrictedShortenService.ShortenRestrictedUrl:output_type -> surl.v1.ShortenRetristedUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_surl_api_proto_init() }
func file_api_v1_surl_api_proto_init() {
	if File_api_v1_surl_api_proto != nil {
		return
	}
	file_api_v1_surl_api_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_surl_api_proto_rawDesc), len(file_api_v1_surl_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_surl_api_proto_goTypes,
		DependencyIndexes: file_api_v1_surl_api_proto_depIdxs,
		MessageInfos:      file_api_v1_surl_api_proto_msgTypes,
	}.Build()
	File_api_v1_surl_api_proto = out.File
	file_api_v1_surl_api_proto_goTypes = nil
	file_api_v1_surl_api_proto_depIdxs = nil
}
