// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/v1/surl/api.proto

package surl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RestrictedShortenService_ShortenRestrictedUrl_FullMethodName = "/surl.v1.RestrictedShortenService/ShortenRestrictedUrl"
)

// RestrictedShortenServiceClient is the client API for RestrictedShortenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestrictedShortenServiceClient interface {
	ShortenRestrictedUrl(ctx context.Context, in *ShortenRestrictedUrlRequest, opts ...grpc.CallOption) (*ShortenRetristedUrlResponse, error)
}

type restrictedShortenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestrictedShortenServiceClient(cc grpc.ClientConnInterface) RestrictedShortenServiceClient {
	return &restrictedShortenServiceClient{cc}
}

func (c *restrictedShortenServiceClient) ShortenRestrictedUrl(ctx context.Context, in *ShortenRestrictedUrlRequest, opts ...grpc.CallOption) (*ShortenRetristedUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortenRetristedUrlResponse)
	err := c.cc.Invoke(ctx, RestrictedShortenService_ShortenRestrictedUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestrictedShortenServiceServer is the server API for RestrictedShortenService service.
// All implementations must embed UnimplementedRestrictedShortenServiceServer
// for forward compatibility.
type RestrictedShortenServiceServer interface {
	ShortenRestrictedUrl(context.Context, *ShortenRestrictedUrlRequest) (*ShortenRetristedUrlResponse, error)
	mustEmbedUnimplementedRestrictedShortenServiceServer()
}

// UnimplementedRestrictedShortenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestrictedShortenServiceServer struct{}

func (UnimplementedRestrictedShortenServiceServer) ShortenRestrictedUrl(context.Context, *ShortenRestrictedUrlRequest) (*ShortenRetristedUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShortenRestrictedUrl not implemented")
}
func (UnimplementedRestrictedShortenServiceServer) mustEmbedUnimplementedRestrictedShortenServiceServer() {
}
func (UnimplementedRestrictedShortenServiceServer) testEmbeddedByValue() {}

// UnsafeRestrictedShortenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestrictedShortenServiceServer will
// result in compilation errors.
type UnsafeRestrictedShortenServiceServer interface {
	mustEmbedUnimplementedRestrictedShortenServiceServer()
}

func RegisterRestrictedShortenServiceServer(s grpc.ServiceRegistrar, srv RestrictedShortenServiceServer) {
	// If the following call panics, it indicates UnimplementedRestrictedShortenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestrictedShortenService_ServiceDesc, srv)
}

func _RestrictedShortenService_ShortenRestrictedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenRestrictedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestrictedShortenServiceServer).ShortenRestrictedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestrictedShortenService_ShortenRestrictedUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestrictedShortenServiceServer).ShortenRestrictedUrl(ctx, req.(*ShortenRestrictedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestrictedShortenService_ServiceDesc is the grpc.ServiceDesc for RestrictedShortenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestrictedShortenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surl.v1.RestrictedShortenService",
	HandlerType: (*RestrictedShortenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShortenRestrictedUrl",
			Handler:    _RestrictedShortenService_ShortenRestrictedUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/surl/api.proto",
}
